### ISSUE TITLE
c42-adbtool.exe exited with error code -1073740791

### ISSUE THREAD

**Issue by christantoan** [thenickdude/c42-adbtool#1]
Using Local Machine install option on Windows 11 x64 machine. CrashPlan version 11.2.1 and using CrashPlan Enterprise subscription.

Here's the last output lines:
```
<omitted>
authority_fallback_list_cleared (hex) = 01
compliance_enforce (hex) = 00 
ssertion failed: key[0] == ADB_KEY_PREFIX[0], file c42-adbtool.cpp, line 95 
c42-adbtool.exe exited on PC5 with error code -1073740791.
```
Hope this can be fixed.
Thank you.
~~Please let me know if you need more info.~~
I've currently uninstalled CrashPlan so I can no longer provide more info. Sorry 🙏

**Comment by thenickdude** [comment]
I've fixed this now, and I'll publish a release with the fix shortly.
